"""
Shared pytest fixtures for DocuMind tests.

All fixtures use files from tests/fixtures/ which are pre-generated by
scripts/create_fixtures.py.  Tests must not require internet access.
"""

from __future__ import annotations

from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ─────────────────────────────────────────────────────────────────────────────
# Paths to fixture files
# ─────────────────────────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def fixtures_dir() -> Path:
    return FIXTURES_DIR


@pytest.fixture(scope="session")
def md_sample(fixtures_dir: Path) -> Path:
    return fixtures_dir / "markdown" / "sample.md"


@pytest.fixture(scope="session")
def md_empty(fixtures_dir: Path) -> Path:
    return fixtures_dir / "markdown" / "empty.md"


@pytest.fixture(scope="session")
def md_no_h1(fixtures_dir: Path) -> Path:
    return fixtures_dir / "markdown" / "no_h1.md"


@pytest.fixture(scope="session")
def html_sample(fixtures_dir: Path) -> Path:
    return fixtures_dir / "html" / "sample.html"


@pytest.fixture(scope="session")
def pdf_sample(fixtures_dir: Path) -> Path:
    return fixtures_dir / "pdf" / "sample.pdf"


@pytest.fixture(scope="session")
def pdf_malformed(fixtures_dir: Path) -> Path:
    return fixtures_dir / "pdf" / "malformed.pdf"


@pytest.fixture(scope="session")
def docx_sample(fixtures_dir: Path) -> Path:
    return fixtures_dir / "docx" / "sample.docx"


@pytest.fixture(scope="session")
def unsupported_csv(fixtures_dir: Path) -> Path:
    return fixtures_dir / "unsupported" / "data.csv"


@pytest.fixture(scope="session")
def unsupported_zip(fixtures_dir: Path) -> Path:
    return fixtures_dir / "unsupported" / "archive.zip"


# ─────────────────────────────────────────────────────────────────────────────
# Loader dispatcher
# ─────────────────────────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def dispatcher():
    from documind.ingestion.loaders import LoaderDispatcher
    return LoaderDispatcher()


# ─────────────────────────────────────────────────────────────────────────────
# Temporary mixed corpus directory
# ─────────────────────────────────────────────────────────────────────────────


@pytest.fixture
def mixed_corpus(tmp_path: Path, md_sample: Path, html_sample: Path,
                 pdf_sample: Path, docx_sample: Path, unsupported_csv: Path) -> Path:
    """A temporary corpus directory with one file of each supported format,
    plus one unsupported file."""
    corpus = tmp_path / "corpus"
    (corpus / "md").mkdir(parents=True)
    (corpus / "html").mkdir(parents=True)
    (corpus / "pdf").mkdir(parents=True)
    (corpus / "docx").mkdir(parents=True)
    (corpus / "other").mkdir(parents=True)

    import shutil
    shutil.copy(md_sample, corpus / "md" / "sample.md")
    shutil.copy(html_sample, corpus / "html" / "sample.html")
    shutil.copy(pdf_sample, corpus / "pdf" / "sample.pdf")
    shutil.copy(docx_sample, corpus / "docx" / "sample.docx")
    shutil.copy(unsupported_csv, corpus / "other" / "data.csv")

    return corpus
